In [1]:
dataDict = np.load('datainput_FinerGrid.npy')[()]
qp.printDictKeys(dataDict)
dataDict['kinCube'].shape, dataDict['potCube'].shape, dataDict['dipCUBE'].shape, dataDict['geoCUBE'].shape

dict_keys(['kinCube', 'potCube', 'dipCUBE', 'geoCUBE', 'phis', 'gams', 'thes'])


((29, 21, 29, 9, 3),
 (29, 21, 29, 8),
 (29, 21, 29, 3, 8, 8),
 (29, 21, 29, 15, 3))

In [2]:
gsm_phi_ind = dataDict['phis'].index('P000-000')
gsm_gam_ind = dataDict['gams'].index('P016-923')
gsm_the_ind = dataDict['thes'].index('P114-804')

gsm_phi_ind, gsm_gam_ind, gsm_the_ind

(14, 10, 14)

In [3]:
from quantumpropagator import labTranformA,fromLabelsToFloats

phiV, gamV, theV = fromLabelsToFloats(dataDict)

phis = labTranformA(dataDict['phis'])
gams = labTranformA(dataDict['gams'])
thes = labTranformA(dataDict['thes'])

phiL = len(phis)
gamL = len(gams)
theL = len(thes)

In [4]:
phis,phiV,phiV[0]-phiV[-1],phiV[0]-phiV[1],phiL

(array([-7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5, -3. , -2.5, -2. ,
        -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
         4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ]),
 array([-0.07 , -0.065, -0.06 , -0.055, -0.05 , -0.045, -0.04 , -0.035,
        -0.03 , -0.025, -0.02 , -0.015, -0.01 , -0.005,  0.   ,  0.005,
         0.01 ,  0.015,  0.02 ,  0.025,  0.03 ,  0.035,  0.04 ,  0.045,
         0.05 ,  0.055,  0.06 ,  0.065,  0.07 ]),
 -0.14000000000000001,
 -0.0050000000000000044,
 29)

In [5]:
gams,gamV,gamV[0]-gamV[-1],gamV[0]-gamV[1],gamL

(array([ 13.846,  14.154,  14.462,  14.769,  15.077,  15.385,  15.692,
         16.   ,  16.308,  16.615,  16.923,  17.231,  17.538,  17.846,
         18.154,  18.462,  18.769,  19.077,  19.385,  19.692,  20.   ]),
 array([ 0.24165829,  0.2470339 ,  0.25240952,  0.25776768,  0.26314329,
         0.26851891,  0.27387707,  0.27925268,  0.28462829,  0.28998646,
         0.29536207,  0.30073768,  0.30609584,  0.31147146,  0.31684707,
         0.32222269,  0.32758085,  0.33295646,  0.33833208,  0.34369024,
         0.34906585]),
 -0.10740756216773104,
 -0.0053756140961425392,
 21)

In [6]:
thes,theV,theV[0]-theV[-1],theV[0]-theV[1], theL

(array([ 121.061,  120.615,  120.168,  119.721,  119.274,  118.827,
         118.38 ,  117.933,  117.486,  117.039,  116.592,  116.145,
         115.698,  115.251,  114.804,  114.358,  113.911,  113.464,
         113.017,  112.57 ,  112.123,  111.676,  111.229,  110.782,
         110.335,  109.888,  109.441,  108.994,  108.547]),
 array([ 1.05645652,  1.05256444,  1.04866363,  1.04476282,  1.04086201,
         1.0369612 ,  1.03306038,  1.02915957,  1.02525876,  1.02135795,
         1.01745714,  1.01355633,  1.00965552,  1.00575471,  1.0018539 ,
         0.99796181,  0.994061  ,  0.99016019,  0.98625938,  0.98235857,
         0.97845776,  0.97455695,  0.97065614,  0.96675533,  0.96285452,
         0.9589537 ,  0.95505289,  0.95115208,  0.94725127]),
 0.10920525129728531,
 0.0038920842319474236,
 29)

In [7]:
dataDict['potCube'].shape, dataDict['kinCube'].shape,

((29, 21, 29, 8), (29, 21, 29, 9, 3))

In [8]:
#dataDict['potCube'] = dataDict['potCube'][:,0:20,:]
#dataDict['kinCube'] = dataDict['kinCube'][:,0:20,:]
#dataDict['potCube'].shape, dataDict['kinCube'].shape, 

In [9]:
#gspotALL = dataDict['potCube']
#gspot = gspotALL[:,:,:,0]
#gspot2 = np.empty_like(gspot)
#gspotALL2 = np.zeros_like(gspotALL)
#
#print(gspot.shape,np.amin(gspot),np.amax(gspot),np.amax(gspot)-np.amin(gspot))#

#p_s = 0.01
#g_s = 100
#t_s = 100
#p0 = phiV[14] 
#g0 = gamV[10]
#t0 = theV[14]

#for pi, p in enumerate(phiV):
#    for gi, g in enumerate(gamV):
#        for ti,t in enumerate(theV):
#             gspot2[pi,gi,ti] = p_s*(p-p0)**2 + g_s*(g-g0)**2 + t_s*(t-t0)**2
#                
#gspotALL2[:,:,:,0] = gspot23

#dataDict['potCube'] = gspotALL2

#saveNew = True
#if saveNew:
#    np.save('datainput_FinerGrid_potential.npy', dataDict)

In [10]:
#%matplotlib notebook
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
from ipywidgets import interact#, interactive, fixed, interact_manual
import ipywidgets as widgets

def do3dplot(xs,ys,zss):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    X,Y = np.meshgrid(ys,xs)
    #ax.plot_wireframe(X, Y, zss)
    ax.scatter(X, Y, zss)
    
def do3dplot2(X,Y,Z):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    #ax.plot_wireframe(X, Y, Z)
    ax.scatter(X, Y, Z)
    


# Potentials

## K matrix elements

In [11]:
def kinElem(mkelem,deriv,phi):
    expl = '{}\'th order derivative coefficient in K matrix'.format(deriv)
    tis = ['Tpp','Tpg','Tpt','Tgp','Tgg','Tgt','Ttp','Ttg','Ttt']
    tisexpl = '{} -> '.format(tis[mkelem])
    print(tisexpl + expl)
    x = gams
    y = thes
    z = dataDict['kinCube'][phi,:,:,mkelem,deriv]
    do3dplot(x,y,z)

interact(kinElem, mkelem = widgets.IntSlider(min=0,max=8,step=1,value=0), deriv = widgets.IntSlider(min=0,max=2,step=1,value=0),phi = widgets.IntSlider(min=0,max=phiL-1,step=1,value=0));

interactive(children=(IntSlider(value=0, description='mkelem', max=8), IntSlider(value=0, description='deriv',…

In [12]:
dataDict['kinCube'][11,10,14],dataDict['kinCube'][8,10,14]

(array([[  0.00000000e+00,   0.00000000e+00,  -8.35472332e-04],
        [  0.00000000e+00,  -2.53570502e-07,  -5.45873123e-07],
        [  0.00000000e+00,  -4.65375191e-09,  -5.66464392e-07],
        [  0.00000000e+00,  -5.37195471e-06,  -5.45873123e-07],
        [ -3.40583407e-07,  -6.69089023e-09,  -6.17230487e-07],
        [ -9.88377667e-12,  -3.81219534e-09,  -3.70111223e-10],
        [  0.00000000e+00,  -5.62130292e-06,  -5.66464392e-07],
        [ -5.51738684e-10,  -3.56685104e-09,  -3.70111223e-10],
        [ -1.81712299e-08,  -7.61215944e-09,  -6.74365133e-07]]),
 array([[  0.00000000e+00,   0.00000000e+00,  -8.35472332e-04],
        [  0.00000000e+00,  -2.53570502e-07,  -5.45873123e-07],
        [  0.00000000e+00,  -4.65375191e-09,  -5.66464392e-07],
        [  0.00000000e+00,  -5.37195471e-06,  -5.45873123e-07],
        [ -3.40583407e-07,  -6.69089023e-09,  -6.17230487e-07],
        [ -9.88377667e-12,  -3.81219534e-09,  -3.70111223e-10],
        [  0.00000000e+00,  -5.6213029

# Double the grid

In [13]:
phiV,gamV,theV

(array([-0.07 , -0.065, -0.06 , -0.055, -0.05 , -0.045, -0.04 , -0.035,
        -0.03 , -0.025, -0.02 , -0.015, -0.01 , -0.005,  0.   ,  0.005,
         0.01 ,  0.015,  0.02 ,  0.025,  0.03 ,  0.035,  0.04 ,  0.045,
         0.05 ,  0.055,  0.06 ,  0.065,  0.07 ]),
 array([ 0.24165829,  0.2470339 ,  0.25240952,  0.25776768,  0.26314329,
         0.26851891,  0.27387707,  0.27925268,  0.28462829,  0.28998646,
         0.29536207,  0.30073768,  0.30609584,  0.31147146,  0.31684707,
         0.32222269,  0.32758085,  0.33295646,  0.33833208,  0.34369024,
         0.34906585]),
 array([ 1.05645652,  1.05256444,  1.04866363,  1.04476282,  1.04086201,
         1.0369612 ,  1.03306038,  1.02915957,  1.02525876,  1.02135795,
         1.01745714,  1.01355633,  1.00965552,  1.00575471,  1.0018539 ,
         0.99796181,  0.994061  ,  0.99016019,  0.98625938,  0.98235857,
         0.97845776,  0.97455695,  0.97065614,  0.96675533,  0.96285452,
         0.9589537 ,  0.95505289,  0.95115208,  0.9472

In [14]:
def expARR(array,howmany):
    dx = array[1]-array[0]
    after = (array[-1] + (dx * np.arange(howmany+1)))[1:]
    before = np.flip((array[0] - (dx * np.arange(howmany+1)))[1:],0)
    return np.concatenate((before,array,after))

def doubleAxespoins(Y):
    N = len(Y)
    X = np.arange(0, 2*N, 2)
    X_new = np.arange(2*N-1)       # Where you want to interpolate
    Y_new = np.interp(X_new, X, Y) 
    return(Y_new)

In [15]:
import quantumpropagator as qp

# gestionate Phi
refi_phi = 2
expandi_phi = 0

phis_n = phiV
phis_n = expARR(phis_n,expandi_phi)
for _ in range(refi_phi):
    phis_n = doubleAxespoins(phis_n)


# gestionate Gam
refi_gam = 2
expandi_gam = 4

gams_n = gamV
gams_n = expARR(gams_n,expandi_gam)
for _ in range(refi_gam):
    gams_n = doubleAxespoins(gams_n)


# gestionate The
refi_the = 2
expandi_the = 0

thes_n = theV
thes_n = expARR(thes_n,expandi_the)
for _ in range(refi_the):
    thes_n = doubleAxespoins(thes_n)

# equilibrium indices and equilibrium points
p0 = phis_n[(gsm_phi_ind+expandi_phi)*2**refi_phi] 
g0 = gams_n[(gsm_gam_ind+expandi_gam)*2**refi_gam]
t0 = thes_n[(gsm_the_ind+expandi_the)*2**refi_the]

print(p0,g0,t0)
    
    
pp,gg,tt = qp.fromFloatsToLabels(phis_n, gams_n, thes_n)
ppL = len(pp)
ggL = len(gg)
ttL = len(tt)

0.0 0.295362069315 1.00185389723


In [16]:
phis_n,gams_n,thes_n

(array([-0.07   , -0.06875, -0.0675 , -0.06625, -0.065  , -0.06375,
        -0.0625 , -0.06125, -0.06   , -0.05875, -0.0575 , -0.05625,
        -0.055  , -0.05375, -0.0525 , -0.05125, -0.05   , -0.04875,
        -0.0475 , -0.04625, -0.045  , -0.04375, -0.0425 , -0.04125,
        -0.04   , -0.03875, -0.0375 , -0.03625, -0.035  , -0.03375,
        -0.0325 , -0.03125, -0.03   , -0.02875, -0.0275 , -0.02625,
        -0.025  , -0.02375, -0.0225 , -0.02125, -0.02   , -0.01875,
        -0.0175 , -0.01625, -0.015  , -0.01375, -0.0125 , -0.01125,
        -0.01   , -0.00875, -0.0075 , -0.00625, -0.005  , -0.00375,
        -0.0025 , -0.00125,  0.     ,  0.00125,  0.0025 ,  0.00375,
         0.005  ,  0.00625,  0.0075 ,  0.00875,  0.01   ,  0.01125,
         0.0125 ,  0.01375,  0.015  ,  0.01625,  0.0175 ,  0.01875,
         0.02   ,  0.02125,  0.0225 ,  0.02375,  0.025  ,  0.02625,
         0.0275 ,  0.02875,  0.03   ,  0.03125,  0.0325 ,  0.03375,
         0.035  ,  0.03625,  0.0375 ,  0.03875, 

In [17]:
print('       |  eq.    #p.     dx       dL')
strngOut = 'Phi:   {:8.4f} {:4} {:10.3e} {:10.3e} \nGamma: {:8.4f} {:4} {:10.3e} {:10.3e} \nTheta: {:8.4f} {:4} {:10.3e} {:10.3e}'
print(strngOut.format(p0,len(phis_n),phis_n[1]-phis_n[0],phis_n[-1]-phis_n[0],g0,len(gams_n), gams_n[1]-gams_n[0],gams_n[-1]-gams_n[0],t0,len(thes_n),thes_n[1]-thes_n[0],thes_n[-1]-thes_n[0]))

       |  eq.    #p.     dx       dL
Phi:     0.0000  113  1.250e-03  1.400e-01 
Gamma:   0.2954  113  1.344e-03  1.504e-01 
Theta:   1.0019  113 -9.730e-04 -1.092e-01


In [ ]:
doublALL = np.zeros((ppL,ggL,ttL))
doublALL2 = np.zeros((ppL,ggL,ttL,8))
kineti = np.zeros((ppL,ggL,ttL,9,3))
smo = np.zeros((ppL,ggL,ttL,3,24))

p_s = 100
g_s = 100
t_s = 100



for pi, p in qp.log_progress(enumerate(phis_n),every=1,size=(len(phis_n))):
    for gi, g in enumerate(gams_n):
        for ti,t in enumerate(thes_n):
            doublALL[pi,gi,ti] = p_s*(p-p0)**2 + g_s*(g-g0)**2 + t_s*(t-t0)**2
            kineti[pi,gi,ti] = qp.calc_g_G(p,g,t)
            smo[pi,gi,ti] = qp.calc_s_mat(p,g,t)
            
doublALL2[:,:,:,0] = doublALL

newdict = {}
newdict['smoCube'] = smo
newdict['kinCube'] = kineti
newdict['potCube'] = doublALL2
newdict['dipCUBE'] = np.zeros((ppL,ggL,ttL,3,8,8))
newdict['geoCUBE'] = np.zeros((ppL,ggL,ttL,3,15))
newdict['phis'] = pp
newdict['gams'] = gg
newdict['thes'] = tt

saveNew = True
if saveNew:
    np.save('doubledoublefinerArmonic.npy', newdict)
    
qp.printDict(newdict)

In [ ]:
newdict['kinCube'].shape

In [ ]:
poten = newdict['potCube'][14,:,14,0]
plt.plot(gams_n,poten_gam)
plt.plot(gams_n,poten_gam)

# Attempt at doing adsorbing potential

In [ ]:
%matplotlib inline

a = 1
b = 50
c = 9
re = np.pi-0.01

x = np.linspace(-10,10,50)

#y = a * (np.arctan(b*(x + c)) + np.arctan(b*(x - c)))

y = a * ((-np.arctan(b*(x + c)) + np.arctan(b*(x - c)))+re)

y = np.where(y<0,0,y)

plt.plot(x,y)

y