In [18]:
dataDict = np.load('datainput_FinerGrid.npy')[()]

In [19]:
qp.printDictKeys(dataDict)

dict_keys(['kinCube', 'potCube', 'dipCUBE', 'geoCUBE', 'phis', 'gams', 'thes'])


In [20]:
dataDict['kinCube'].shape, dataDict['potCube'].shape, dataDict['dipCUBE'].shape, dataDict['geoCUBE'].shape

((29, 21, 29, 9, 3),
 (29, 21, 29, 8),
 (29, 21, 29, 3, 8, 8),
 (29, 21, 29, 15, 3))

In [21]:
gsm_phi_ind = dataDict['phis'].index('P000-000')
gsm_gam_ind = dataDict['gams'].index('P016-923')
gsm_the_ind = dataDict['thes'].index('P114-804')

In [22]:
gsm_phi_ind, gsm_gam_ind, gsm_the_ind

(14, 10, 14)

In [23]:
from quantumpropagator import labTranformA,fromLabelsToFloats

phiV, gamV, theV = fromLabelsToFloats(dataDict)

phis = labTranformA(dataDict['phis'])
gams = labTranformA(dataDict['gams'])
thes = labTranformA(dataDict['thes'])

phiL = len(phis)
gamL = len(gams)
theL = len(thes)

In [24]:
phis,phiV

(array([-7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5, -3. , -2.5, -2. ,
        -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
         4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ]),
 array([-1.16666667, -1.08333333, -1.        , -0.91666667, -0.83333333,
        -0.75      , -0.66666667, -0.58333333, -0.5       , -0.41666667,
        -0.33333333, -0.25      , -0.16666667, -0.08333333,  0.        ,
         0.08333333,  0.16666667,  0.25      ,  0.33333333,  0.41666667,
         0.5       ,  0.58333333,  0.66666667,  0.75      ,  0.83333333,
         0.91666667,  1.        ,  1.08333333,  1.16666667]))

In [25]:
0.24165829-0.2470339

-0.005375610000000003

In [26]:
gams,gamV

(array([ 13.846,  14.154,  14.462,  14.769,  15.077,  15.385,  15.692,
         16.   ,  16.308,  16.615,  16.923,  17.231,  17.538,  17.846,
         18.154,  18.462,  18.769,  19.077,  19.385,  19.692,  20.   ]),
 array([ 0.24165829,  0.2470339 ,  0.25240952,  0.25776768,  0.26314329,
         0.26851891,  0.27387707,  0.27925268,  0.28462829,  0.28998646,
         0.29536207,  0.30073768,  0.30609584,  0.31147146,  0.31684707,
         0.32222269,  0.32758085,  0.33295646,  0.33833208,  0.34369024,
         0.34906585]))

In [27]:
thes,theV

(array([ 121.061,  120.615,  120.168,  119.721,  119.274,  118.827,
         118.38 ,  117.933,  117.486,  117.039,  116.592,  116.145,
         115.698,  115.251,  114.804,  114.358,  113.911,  113.464,
         113.017,  112.57 ,  112.123,  111.676,  111.229,  110.782,
         110.335,  109.888,  109.441,  108.994,  108.547]),
 array([ 1.05645652,  1.05256444,  1.04866363,  1.04476282,  1.04086201,
         1.0369612 ,  1.03306038,  1.02915957,  1.02525876,  1.02135795,
         1.01745714,  1.01355633,  1.00965552,  1.00575471,  1.0018539 ,
         0.99796181,  0.994061  ,  0.99016019,  0.98625938,  0.98235857,
         0.97845776,  0.97455695,  0.97065614,  0.96675533,  0.96285452,
         0.9589537 ,  0.95505289,  0.95115208,  0.94725127]))

In [11]:
dataDict['potCube'].shape, dataDict['kinCube'].shape,

((29, 21, 29, 8), (29, 21, 29, 9, 3))

In [12]:
#dataDict['potCube'] = dataDict['potCube'][:,0:20,:]
#dataDict['kinCube'] = dataDict['kinCube'][:,0:20,:]
#dataDict['potCube'].shape, dataDict['kinCube'].shape, 

In [13]:
qp.fromHartoEv(0.207797710364)

5.65446703139437

In [14]:
gspotALL = dataDict['potCube']
gspot = gspotALL[:,:,:,0]
gspot2 = np.empty_like(gspot)
gspotALL2 = np.zeros_like(gspotALL)

print(gspot.shape,np.amin(gspot),np.amax(gspot),np.amax(gspot)-np.amin(gspot))

p_s = 0.01
g_s = 1
t_s = 1
p0 = phiV[14] 
g0 = gamV[10]
t0 = theV[14]

for pi, p in enumerate(phiV):
    for gi, g in enumerate(gamV):
        for ti,t in enumerate(theV):
             gspot2[pi,gi,ti] = p_s*(p-p0)**2 + g_s*(g-g0)**2 + t_s*(t-t0)**2
                
gspotALL2[:,:,:,0] = gspot2

dataDict['potCube'] = gspotALL2

saveNew = True
if saveNew:
    np.save('datainput_FinerGrid_potential.npy', dataDict)

(29, 21, 29) -269.70609157 -269.498293859 0.207797710364


In [15]:
%matplotlib notebook
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
from ipywidgets import interact#, interactive, fixed, interact_manual
import quantumpropagator as qp
import ipywidgets as widgets

def do3dplot(xs,ys,zss):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    X,Y = np.meshgrid(ys,xs)
    #ax.plot_wireframe(X, Y, zss)
    ax.scatter(X, Y, zss)
    
def do3dplot2(X,Y,Z):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    #ax.plot_wireframe(X, Y, Z)
    ax.scatter(X, Y, Z)
    


# Potentials

## K matrix elements

In [17]:
def kinElem(mkelem,deriv,phi):
    expl = '{}\'th order derivative coefficient in K matrix'.format(deriv)
    tis = ['Tpp','Tpg','Tpt','Tgp','Tgg','Tgt','Ttp','Ttg','Ttt']
    tisexpl = '{} -> '.format(tis[mkelem])
    print(tisexpl + expl)
    x = gams
    y = thes
    z = dataDict['kinCube'][phi,:,:,mkelem,deriv]
    do3dplot(x,y,z)

interact(kinElem, mkelem = widgets.IntSlider(min=0,max=8,step=1,value=0), deriv = widgets.IntSlider(min=0,max=2,step=1,value=0),phi = widgets.IntSlider(min=0,max=phiL-1,step=1,value=0));

interactive(children=(IntSlider(value=0, description='mkelem', max=8), IntSlider(value=0, description='deriv',…